### PR TITLE
Upgrade requirements

### PR DESCRIPTION
**Pull request by dingedi**
It seems to work without problems, there does not seem to have been any BC

### CODE REVIEW

**Comment by PJ-Finlay** [comment]
CTranslate2 SentencePiece upgrades are good, I'm pretty sure we're tied to the specific Stanza version that's packaged with the models.

**Comment by dingedi** [comment]
alright, is there any way to check?  because the unit tests went well.  otherwise I put the old version back.

**Comment by PJ-Finlay** [comment]
I'm pretty sure we can't upgrade Stanza, if you try doing a translation with a newer version I think it will break. If we're updating CTranslate2 we should also convert to the new TranslationResult object.

- https://github.com/OpenNMT/CTranslate2/releases/tag/v2.4.0

**Comment by dingedi** [comment]
I am not really a pro in python, a bit hard for me I think of replacing with TranslationResult

**Pull request merged**
