### PR TITLE
remove deprecated load_installed_languages()

### PR DESCRIPTION
**Pull request by dingedi**

### CODE REVIEW

**Review by argosopentech — CHANGES_REQUESTED** [review]
Can you just do the cli.py change? 

I have the translate.py change on the v2 branch: 
https://github.com/argosopentech/argos-translate/pull/287/commits/ca40fdc552eea174a60e74e364fa31968719d602

**Comment by argosopentech** [comment]
I think this needs to be update in LibreTranslate as well:
https://github.com/LibreTranslate/LibreTranslate/blob/7b7cd7768b1eec75fb95cf820b0cb03ad14b16b8/app/init.py#L58

**Comment by dingedi** [comment]
it should be ok now

**Comment by dingedi** [comment]
Done for LibreTranslate in [https://github.com/LibreTranslate/LibreTranslate/pull/313](https://github.com/LibreTranslate/LibreTranslate/pull/313)

**Comment by PJ-Finlay** [comment]
Thanks!

**Pull request merged**
