### PR TITLE
Add python type hints

### PR DESCRIPTION
**Pull request by dingedi**
Close https://github.com/argosopentech/argos-translate/issues/289

### CODE REVIEW

**Comment by pierotofy** [comment]
Nice!

**Comment by dingedi** [comment]
I just saw that using union type (ex: str | None ) can only be used for python 3.10 minimum

currently it causes this error: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'


do we put a minimum of python 3.10 for argos? seems a bit high knowing that libretranslate still supports it since python 3.7
or else use types except union types for now

**Comment by dingedi** [comment]
finally by using
```python
from __future__ import annotations
```
this makes it possible to use type unions and other things in older versions of python.

**Comment by PJ-Finlay** [comment]
Awesome thanks! 🚀

I agree with using the future module. I don't want to put too much effort into maintaining support for older Python versions but 9.10 is pretty bleeding edge.

**Comment by PJ-Finlay** [comment]
I merged this into the v2 branch as well.

https://github.com/argosopentech/argos-translate/commit/ef583a73f85f8a94388b8b8733af235834e8df20

**Pull request merged**
