### PR TITLE
Upgrade ctranslate2 to version 4

### PR DESCRIPTION
**Pull request by ddorian**

### CODE REVIEW

**Comment by yudelevi** [comment]
I am not a maintainer, but I've been running with CTranslate2-4.0.0 for a while and just upgraded to CTranslate2-4.1.0 and didn't run into any issues

**Comment by PJ-Finlay** [comment]
> I am not a maintainer, but I've been running with CTranslate2-4.0.0 for a while and just upgraded to CTranslate2-4.1.0 and didn't run into any issues

Good to know thanks.

Does anyone know what's new in CTranslate2 v4? I'm not seeing anything on the OpenNMT forum, Github, or the docs. They had a post on the forum for v2 and v3.

I generally take a somewhat slow approach to updating unless the new version has something we need just to let other people find all the bugs first. I'll probably update eventually though. 

Also I updated another line in requirements.txt so this commit has a merge conflict now.

**Comment by yudelevi** [comment]
I upgraded because of CUDA 12 support. I rent GPUs from various providers, and CUDA12 is now the norm.

**Comment by PJ-Finlay** [comment]
> I upgraded because of CUDA 12 support. I rent GPUs from various providers, and CUDA12 is now the norm.

That makes sense. I'll upgrade now

**Pull request merged**
