### PR TITLE
BPE encoding, prefix/suffix support, NLLB support

### PR DESCRIPTION
**Pull request by pierotofy**
Following up on the discussion at https://community.libretranslate.com/t/proposal-to-extend-the-argospackage-format/737/11, I've implemented some changes that allow:
 * Conversion and inference of OPUS-MT models that use BPE encoding instead of SentencePiece. This involves the addition of just one dependency (sacremoses), which I don't think is worth refactoring due to the large number of data files it requires for installation. Leaving it as a dependency will make updates easier. `apply_bpe.py` from subword-nmt has been included almost as-is, so no need for adding a dependency to subword-nmt.
  * I added the ability to specify a (optional) `target_prefix` in the manifest: you can now specify the target_prefix parameter that is sent to `translate_batch`, which allows the argosmodel spec to use multilingual models such as NLLB, for example:

Link to `en-it` NLLB model: https://drive.google.com/file/d/1PmBeXhm0QwaOknJPauBn44nF_bR9dfON/view?usp=sharing

```bash
import argostranslate.package
import argostranslate.translate

# Translate
s = "When people don't see moose as potentially dangerous, they may approach too closely and put themselves at risk."
print(argostranslate.translate.translate(s, "en", "it"))
```

Output: `Quando le persone non vedono l'alce come potenzialmente pericoloso, possono avvicinarsi troppo e mettersi a rischio.`

```json
{
    "argos_version": "1.8.2",
    "from_code": "en",
    "from_name": "English",
    "package_version": "1.0",
    "to_code": "it",
    "to_name": "Italian",
    "target_prefix": "ita_Latn"
}
```

Which is kind of neat, because you can switch the target prefix and get a different language output. E.g. for Friulano `fur_Latn`: 

```
Cuant che la int no viôt l'alc come potenzialmentri periculôs, e podarès slargjâsi trop dongje e metisi in pericul.
```

Eventually this could be easily extended to support dynamic metavars, e.g. allow `target_prefix` to be something like `%(tgt_lang)`, and replace that value at runtime to match the requested language, but that's left as an exercise for a later PR.

### CODE REVIEW

**Comment by pierotofy** [comment]
I wasn't sure on the naming of `tokens_prefix` (should it be `source_prefix`? ), so if you want to rename things, feel free.

**Comment by pierotofy** [comment]
Link to BPE encoded model (Greek -> English):

https://drive.google.com/file/d/1UY5zZHRBLVTuDrPogQXfwNmW7A2YZlrZ/view?usp=sharing

```python
import argostranslate.package
import argostranslate.translate

# Translate
s = "Όταν οι άνθρωποι δεν βλέπουν τους τάρανδοι ως δυνητικά επικίνδυνους, μπορεί να πλησιάσουν πολύ κοντά και να θέσουν τον εαυτό τους σε κίνδυνο."
print(argostranslate.translate.translate(s, "el", "en"))
```

Output: `When people don't see the rein deer as potentially dangerous, they can get very close and put themselves in danger.`

One possible bug I found out while implementing this is that on certain machines (Linux with no GPU), for some reason ctranslate2 fails to translate the OPUS-MT model by generating garbage:

```
denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin denomin ....
```

I've narrowed down the problem to the `compute_type` parameter for runtime quantization; for some reason, some of these models fail when compute_type is set to `default` (the current value). Forcing the model to use "float32" fixes the problem, but I'm unsure of the root cause

Edit this line in `translate.py`:

```python
self.translator = ctranslate2.Translator(model_path, device=settings.device, compute_type="float32")
```

**Comment by pierotofy** [comment]
`float32` quantized Greek -> English model (use this one to test if you get the garbage issue with the smaller int8 model): https://drive.google.com/file/d/1Rltpes7jLmXrE6LEc5nFNeAyjyQxQ8p8/view?usp=drive_link

It does seem an issue with ctranslate2, when I have time I will dig a bit deeper to see what's going on. We definitely don't want to set arbitrary `compute_type` values.

**Comment by argosopentech** [comment]
Awesome thanks! This looks great

**Pull request merged**
