### PR TITLE
Start tests

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
This starts the fix to #11 
Write tests for most classes and methods in `translate.py`
This is just a start to writing the tests for this project, and this PR is just to kick-start that process.

This PR contains tests for the following classes including all of their methods
- Hypothesis
- ITranslation
- Language
- IdentityTranslation
- CompositeTranslation

### CODE REVIEW

**Comment by PJ-Finlay** [comment]
Great thanks a lot!

Why pytest instead of the standard library's [unittest](https://docs.python.org/3/library/unittest.html)? In general I've tried to keep dependencies to a minimum when possible.

**Comment by JakeRoggenbuck** [comment]
No problem! I've worked with pytest a bit more than unittest. They're both nice but I think pytest has more features. I'd be happy to move towards unittest if you think it's best for the project.

**Comment by PJ-Finlay** [comment]
Sounds good, no reason to immediately rewrite but I think unittest is the direction we want to go in long term. Thanks again for getting this started!

**Comment by JakeRoggenbuck** [comment]
Yea, I can switch the tests over to unittest at some point, and ofc! This is an awesome project!

**Comment by PJ-Finlay** [comment]
Thanks! Actually I've been reading a bit and I think pytest may actually be the better choice. It sounds like besides not being in the standard library it's much better. Most of our dependency issues have been with packaging and we can always package a version without the unit tests.

**Comment by JakeRoggenbuck** [comment]
Alright, sounds great!

**Pull request merged**
