### PR TITLE
Having possibilty of multiple translation suggested

### PR DESCRIPTION
**Pull request by mmokhi**
This change makes it possible to pass `num_hypotheses` and `beam_size` to CTranslate and have multiple results returned.
Results will be combined and compiled into a list and returned.

The new functionality is called `multi_translate()` and this change keeps old API of `translate()` as wrapper of that, in which default parameters will be passed, and also the return value will be of type `str` as before (instead of new `[str]`)

### CODE REVIEW

**Comment by PJ-Finlay** [comment]
This is great, I think we'll need this for doing XML translations. Thanks!

**Comment by mmokhi** [comment]
> This is great, I think we'll need this for doing XML translations. Thanks!

Glad to hear it is a useful contribution :raised_hands:  :grin: :blush:

**Comment by PJ-Finlay** [comment]
Just added scores for hypotheses so you will be able to do:
```
hypotheses = translation_en_es.hypotheses('Hello World')
for hypothesis in hypotheses:
    print(f'{hypothesis.score} - {hypothesis.output}')

# Output
-1.134260654449463 - Hola Mundo
-2.1044602394104004 - Hola World
-2.9032299518585205 - Hello World
-4.167231559753418 - Hola, Mundo
```

**Comment by mmokhi** [comment]
> Just added scores for hypotheses so you will be able to do:
> 
> ```
> hypotheses = translation_en_es.hypotheses('Hello World')
> for hypothesis in hypotheses:
>     print(f'{hypothesis.score} - {hypothesis.output}')
> 
> # Output
> -1.134260654449463 - Hola Mundo
> -2.1044602394104004 - Hola World
> -2.9032299518585205 - Hello World
> -4.167231559753418 - Hola, Mundo
> ```

That's very useful :star_struck: thanks :raised_hands:

**Pull request merged**
